### ISSUE TITLE
Great idea with a new guide for beginners (like me). Issue

### ISSUE THREAD

**Issue by wormiedk** [JanLoebel/eufy-node-client-examples#1]
Hi.

You might want to include a cd eufy-node-client-examples after the git clone.

I was working my way through the guide and got to inserting credentials in the .env file and running node examples/http-read-data/index.js
this gives the following error:
`Starting...
No credentials found -> register new...
(node:2486697) UnhandledPromiseRejectionWarning: TypeError: HttpService is not a constructor
    at main (/home/media/eufy-node-client-examples/examples/http-read-data/index.js:12:23)
    at Object.<anonymous> (/home/media/eufy-node-client-examples/examples/http-read-data/index.js:25:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:2486697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2486697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2486697) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/media/eufy-node-client-examples/node_modules/eufy-node-client/build/push/checkin.proto'
(node:2486697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

npm install returned
`pm WARN eufy-node-client-examples@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`

**Comment by JanLoebel** [comment]
You're totally right:
- I've made a mistake there, please go into the eufy-node-client-examples directory and execute `git pull` and then `npm install`. Afterwards try to run `node examples/http-read-data/index.js` again.

- Thanks for the tip with the directory change, I've added the command to the tutorial!

Please let me know if it works now.

**Comment by Roadrunner1106** [comment]
I had the same error and it is now fixed with your changes.

The call of "node examples/http-read-data/index.js" works now.

When calling "node examples/p2p-local/index.js" it hangs when sending the ARMING command. Here the log (IP ist masked by me).

```
Found address { host: '192.168.x.xxx', port: 21068 }
connected!
Sending commandType: CMD_SET_ARMING (1224) with seqNum: 0...
ACK for seqNo: 0
DATA package with commandId: CMD_SET_ARMING (1224) - data: 65420
```

But der Mode is correct switch to ARMED_HOME.

**Comment by JanLoebel** [comment]
The reason for that is that the current implementation is waiting for messages of the home station. We would have to implement a `disconnect` method which could be called to stop listening. I will create an issue in the main `eufy-node-client` repository for that.

**Comment by wormiedk** [comment]
Works great now with the homebase 👍  
Would be great if it automatically disconnected after setting mode
I also have an indoor cam which the code does not found even if I hardcode the ip of the indoor cam into the .env file

**Comment by JanLoebel** [comment]
@wormiedk 
I don't have an indoor cam, send me one or the money and I can see If I can get it working ;)

**Comment by wormiedk** [comment]
Sounds like a plan :) 

I got the command to exit by using this code:

```
const dotenv = require('dotenv');
const { LocalLookupService, DeviceClientService, CommandType } = require('eufy-node-client');

dotenv.config();
const LOCAL_STATION_IP = process.env.LOCAL_STATION_IP;
const P2P_DID = process.env.P2P_DID;
const ACTOR_ID = process.env.ACTOR_ID;
if (!LOCAL_STATION_IP || !P2P_DID || !ACTOR_ID) {
  throw new Error(`Please fill in 'LOCAL_STATION_IP' & 'P2P_DID' & 'ACTOR_ID' values in your .env-file!`);
}

const main = async () => {
  const lookupService = new LocalLookupService();
  const address = await lookupService.lookup(LOCAL_STATION_IP);
  console.log('Found address', address);

  const devClientService = new DeviceClientService(address, P2P_DID, ACTOR_ID);
  await devClientService.connect();

  // CMD_SET_ARMING  # 0 => away 1 => home, 2 => schedule, 63 => disarmed
  devClientService.sendCommandWithInt(CommandType.CMD_SET_ARMING, 1);
  await sleep(5000);
  process.exit();
};

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
};
main();

```
