### ISSUE TITLE
Idiot's guide to adding to NodeRed

### ISSUE THREAD

**Issue by PeteBurgess** [JanLoebel/eufy-node-client-examples#3]
Is there something of an idiot's guide to adding this to NodeRed ? Currently all I want to do is to receive a notification from the doorbell's motion sensor. I'm sure I can modify the example to do so, however NodeRed is completely new to me, as is most home automation. I don't mind learning, I don't mind Googling, but a shove in the right direction would be nice.

**Comment by JanLoebel** [comment]
I don't know NodeRed and how it works, if you want to receive push notifications an idea could be to forward push notifications to a mqtt-broker. node-red has a mqtt-connector so it could receive that event there. @PeteBurgess please investigate further if an MQTT connection would be helpful, if so we could add an example for that.

**Comment by PeteBurgess** [comment]
That makes two of us.

Currently I don’t get any actions relating to this showing up in Node-Red and that’s really what my issue is. If I can MQTT after that, that’ll work great. Ultimately my goal is to have this controlled by HomeKit via Homebridge... motion sensor in the doorbell triggers, HomeKit turns on the floodlights.

NPM still shows as installing v0.1 rather than 0.2, btw.

**Comment by JanLoebel** [comment]
@PeteBurgess okay, then one of my next examples will be the push2mqtt integration.

NPM was right, the version in the master branch is always one step ahead the released version.

**Comment by JanLoebel** [comment]
Please update and checkout `push-mqtt`.

**Comment by PeteBurgess** [comment]
Thanks, I’ll have a crack at it over the weekend.
