### ISSUE TITLE
Unable to change HomeBase guard mode but works for indoor 2k cam

### ISSUE THREAD

**Issue by xraywinedrinker** [JanLoebel/eufy-node-client-examples#7]
I realize that this client is now deprecated but I am no longer able to change the guard mode on the HomeBase. Running the node command in terminal, it shows connected and sent but the mode status doesn't change. I can see the HomeBase through the node http lookup and can change the guard mode of the indoor 2k cameras. 

Any idea why this stopped functioning?

**Comment by JanLoebel** [comment]
@xraywinedrinker Sorry, no idea what happened there. And yes it's deprecated. Please use: https://github.com/bropat/eufy-security-client

**Comment by xraywinedrinker** [comment]
Unfortunately, I don't know how to create the node.js file like your example to use the Eufy-security-nodes. I was able to use your example for a while.
